-- AkaAka consolidated schema baseline
-- Generated by concatenating historical migrations in timestamp order.
-- This file preserves the complete current schema for fresh environments and db reset.
-- Hosted Supabase projects retain their existing migration history; do not push this baseline
-- against a project whose migration history has been reset.
--
-- BEGIN HISTORICAL MIGRATION: 20260717000001_initial_schema.sql
--
-- AkaAka initial schema
-- Matches the current remote database state as of 2026-07-17

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1) profiles
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role_status TEXT NOT NULL DEFAULT 'general'
    CHECK (role_status IN ('general', 'venue_pending', 'venue_approved')),
  display_name TEXT,
  bio TEXT,
  external_social_links JSONB NOT NULL DEFAULT '[]'::jsonb,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  venue_metadata JSONB DEFAULT NULL,
  reputation_score INT NOT NULL DEFAULT 0 CHECK (reputation_score >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW())
);

ALTER TABLE profiles
ADD CONSTRAINT profiles_social_links_min_one
CHECK (
  external_social_links IS NOT NULL
  AND jsonb_typeof(external_social_links) = 'array'
  AND jsonb_array_length(external_social_links) >= 1
);

-- 2) events
CREATE TABLE IF NOT EXISTS events (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  creator_id UUID NOT NULL REFERENCES profiles(id),
  title TEXT NOT NULL,
  description TEXT,
  event_type TEXT NOT NULL,
  is_venue_hosted BOOLEAN NOT NULL DEFAULT FALSE,
  visibility_settings JSONB NOT NULL DEFAULT '{"type":"public"}'::jsonb,
  start_time TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW())
);

-- 3) event_threads
CREATE TABLE IF NOT EXISTS event_threads (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  event_id UUID NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  profile_id UUID NOT NULL REFERENCES profiles(id),
  content TEXT NOT NULL,
  parent_id UUID REFERENCES event_threads(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW())
);

-- 4) recommendations
CREATE TABLE IF NOT EXISTS recommendations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  from_profile_id UUID NOT NULL REFERENCES profiles(id),
  to_profile_id UUID NOT NULL REFERENCES profiles(id),
  score_increment INT NOT NULL DEFAULT 1 CHECK (score_increment > 0),
  comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW()),
  CONSTRAINT recommendations_no_self_recommendation CHECK (from_profile_id <> to_profile_id)
);

-- 5) blocks
CREATE TABLE IF NOT EXISTS blocks (
  blocker_id UUID NOT NULL REFERENCES profiles(id),
  blocked_id UUID NOT NULL REFERENCES profiles(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW()),
  PRIMARY KEY (blocker_id, blocked_id),
  CHECK (blocker_id <> blocked_id)
);

-- 6) reports
CREATE TABLE IF NOT EXISTS reports (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  reporter_id UUID NOT NULL REFERENCES profiles(id),
  target_profile_id UUID REFERENCES profiles(id),
  target_event_id UUID REFERENCES events(id),
  category TEXT NOT NULL CHECK (category IN ('harassment', 'impersonation', 'spam', 'safety_risk', 'other')),
  details TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'triaging', 'resolved', 'rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW()),
  resolved_at TIMESTAMPTZ
);

-- 7) moderation_actions
CREATE TABLE IF NOT EXISTS moderation_actions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  report_id UUID REFERENCES reports(id) ON DELETE SET NULL,
  admin_id UUID NOT NULL REFERENCES profiles(id),
  action_type TEXT NOT NULL CHECK (action_type IN ('warn', 'suspend', 'ban', 'role_upgrade', 'role_revoke', 'note')),
  target_profile_id UUID REFERENCES profiles(id),
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW())
);

-- 8) audit_logs
CREATE TABLE IF NOT EXISTS audit_logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  actor_id UUID NOT NULL REFERENCES profiles(id),
  target_profile_id UUID REFERENCES profiles(id),
  action TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW())
);

-- 9) issues
CREATE TABLE IF NOT EXISTS issues (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  reporter_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  log_url TEXT,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW())
);

-- 10) issue_comments
CREATE TABLE IF NOT EXISTS issue_comments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  issue_id UUID NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW())
);

-- RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE moderation_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE issues ENABLE ROW LEVEL SECURITY;
ALTER TABLE issue_comments ENABLE ROW LEVEL SECURITY;

-- profiles
CREATE POLICY profiles_read_all ON profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY profiles_update_self ON profiles FOR UPDATE TO authenticated
USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- events
CREATE POLICY events_read_all ON events FOR SELECT TO authenticated USING (true);
CREATE POLICY events_insert_owner ON events FOR INSERT TO authenticated
WITH CHECK (
  creator_id = auth.uid()
  AND (
    is_venue_hosted = false
    OR EXISTS (
      SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role_status = 'venue_approved'
    )
  )
);
CREATE POLICY events_update_owner ON events FOR UPDATE TO authenticated
USING (creator_id = auth.uid()) WITH CHECK (creator_id = auth.uid());

-- event_threads
CREATE POLICY threads_read_all ON event_threads FOR SELECT TO authenticated USING (true);
CREATE POLICY threads_insert_owner ON event_threads FOR INSERT TO authenticated
WITH CHECK (profile_id = auth.uid());
CREATE POLICY threads_update_owner ON event_threads FOR UPDATE TO authenticated
USING (profile_id = auth.uid()) WITH CHECK (profile_id = auth.uid());

-- recommendations
CREATE POLICY recommendations_read_all ON recommendations FOR SELECT TO authenticated USING (true);
CREATE POLICY recommendations_insert_self ON recommendations FOR INSERT TO authenticated
WITH CHECK (from_profile_id = auth.uid());

-- blocks
CREATE POLICY blocks_read_owner ON blocks FOR SELECT TO authenticated
USING (blocker_id = auth.uid());
CREATE POLICY blocks_insert_owner ON blocks FOR INSERT TO authenticated
WITH CHECK (blocker_id = auth.uid());
CREATE POLICY blocks_delete_owner ON blocks FOR DELETE TO authenticated
USING (blocker_id = auth.uid());

-- reports
CREATE POLICY reports_insert_owner ON reports FOR INSERT TO authenticated
WITH CHECK (reporter_id = auth.uid());
CREATE POLICY reports_read_owner ON reports FOR SELECT TO authenticated
USING (reporter_id = auth.uid() OR auth.jwt() ->> 'role' = 'admin');

-- moderation_actions
CREATE POLICY moderation_actions_admin_rw ON moderation_actions FOR ALL TO authenticated
USING (auth.jwt() ->> 'role' = 'admin')
WITH CHECK (auth.jwt() ->> 'role' = 'admin');

-- audit_logs
CREATE POLICY audit_logs_admin_read ON audit_logs FOR SELECT TO authenticated
USING (auth.jwt() ->> 'role' = 'admin');
CREATE POLICY audit_logs_system_insert ON audit_logs FOR INSERT TO authenticated
WITH CHECK (auth.jwt() ->> 'role' = 'admin');

-- issues
CREATE POLICY issues_insert_owner ON issues FOR INSERT TO authenticated
WITH CHECK (reporter_id = auth.uid());
CREATE POLICY issues_read_owner ON issues FOR SELECT TO authenticated
USING (reporter_id = auth.uid() OR auth.jwt() ->> 'role' = 'admin');
CREATE POLICY issues_update_admin ON issues FOR UPDATE TO authenticated
USING (auth.jwt() ->> 'role' = 'admin')
WITH CHECK (auth.jwt() ->> 'role' = 'admin');

-- issue_comments
CREATE POLICY issue_comments_insert_auth ON issue_comments FOR INSERT TO authenticated
WITH CHECK (profile_id = auth.uid());
CREATE POLICY issue_comments_read_members ON issue_comments FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM issues i
    WHERE i.id = issue_id
      AND (i.reporter_id = auth.uid() OR auth.jwt() ->> 'role' = 'admin')
  )
);

-- Triggers
CREATE OR REPLACE FUNCTION apply_recommendation_score()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  weight NUMERIC := 1.0;
BEGIN
  IF EXISTS (
    SELECT 1 FROM profiles p
    WHERE p.id = NEW.from_profile_id
      AND p.role_status = 'venue_approved'
  ) THEN
    weight := 1.5;
  END IF;

  UPDATE profiles
  SET reputation_score = reputation_score + CEIL(NEW.score_increment * weight)::INT
  WHERE id = NEW.to_profile_id;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_apply_recommendation_score ON recommendations;
CREATE TRIGGER trg_apply_recommendation_score
AFTER INSERT ON recommendations
FOR EACH ROW
EXECUTE FUNCTION apply_recommendation_score();

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = TIMEZONE('utc', NOW());
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_issues_updated_at ON issues;
CREATE TRIGGER trg_issues_updated_at
BEFORE UPDATE ON issues
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_profiles_metadata_gin ON profiles USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_profiles_social_links_gin ON profiles USING GIN (external_social_links);
CREATE INDEX IF NOT EXISTS idx_events_visibility_gin ON events USING GIN (visibility_settings);
CREATE INDEX IF NOT EXISTS idx_reports_status_created_at ON reports (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_issues_status_created_at ON issues (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_issues_reporter_id ON issues (reporter_id);
CREATE INDEX IF NOT EXISTS idx_issue_comments_issue_id ON issue_comments (issue_id);

-- END HISTORICAL MIGRATION: 20260717000001_initial_schema.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260717000002_add_issues_tables.sql
--
-- Add issues and issue_comments tables (missing from remote DB)
-- Previous tables already exist

-- issues
CREATE TABLE IF NOT EXISTS issues (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reporter_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  log_url TEXT,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW())
);

-- issue_comments
CREATE TABLE IF NOT EXISTS issue_comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  issue_id UUID NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW())
);

-- RLS
ALTER TABLE issues ENABLE ROW LEVEL SECURITY;
ALTER TABLE issue_comments ENABLE ROW LEVEL SECURITY;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_issues_status_created_at ON issues (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_issues_reporter_id ON issues (reporter_id);
CREATE INDEX IF NOT EXISTS idx_issue_comments_issue_id ON issue_comments (issue_id);

-- updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = TIMEZONE('utc', NOW());
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_issues_updated_at ON issues;
CREATE TRIGGER trg_issues_updated_at
BEFORE UPDATE ON issues
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- END HISTORICAL MIGRATION: 20260717000002_add_issues_tables.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260717000003_add_missing_triggers_and_policy.sql
--
-- Add missing triggers and policy not covered by initial schema

-- ─── Audit log: profile role_status change ─────────────────────────────────
-- Logs when role_status actually changes on a profile row.
-- SECURITY DEFINER so the trigger can bypass RLS on audit_logs.

CREATE OR REPLACE FUNCTION log_role_status_change()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF OLD.role_status IS DISTINCT FROM NEW.role_status THEN
    INSERT INTO audit_logs (actor_id, target_profile_id, action, payload)
    VALUES (
      COALESCE(auth.uid(), NEW.id),
      NEW.id,
      'role_status_change',
      jsonb_build_object('old', OLD.role_status, 'new', NEW.role_status)
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_log_role_status_change ON profiles;
CREATE TRIGGER trg_log_role_status_change
  AFTER UPDATE ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION log_role_status_change();

-- ─── Audit log: moderation action inserted ─────────────────────────────────
-- Every new row in moderation_actions produces an audit_logs entry.
-- SECURITY DEFINER so the trigger can bypass RLS on audit_logs.

CREATE OR REPLACE FUNCTION log_moderation_action()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO audit_logs (actor_id, target_profile_id, action, payload)
  VALUES (
    NEW.admin_id,
    NEW.target_profile_id,
    NEW.action_type,
    NEW.payload
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_log_moderation_action ON moderation_actions;
CREATE TRIGGER trg_log_moderation_action
  AFTER INSERT ON moderation_actions
  FOR EACH ROW
  EXECUTE FUNCTION log_moderation_action();

-- ─── Recommendation rate limit (DB-level guard) ────────────────────────────
-- Enforces 1 recommendation per 24h per target at the database level,
-- catching any inserts that bypass the Edge Function.

CREATE OR REPLACE FUNCTION check_recommendation_rate_limit()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  rec_count INT;
BEGIN
  SELECT COUNT(*) INTO rec_count
  FROM recommendations
  WHERE from_profile_id = NEW.from_profile_id
    AND to_profile_id = NEW.to_profile_id
    AND created_at > NOW() - INTERVAL '24 hours';

  IF rec_count >= 1 THEN
    RAISE EXCEPTION 'rate_limited: already recommended this person in the last 24 hours';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_check_recommendation_rate_limit ON recommendations;
CREATE TRIGGER trg_check_recommendation_rate_limit
  BEFORE INSERT ON recommendations
  FOR EACH ROW
  EXECUTE FUNCTION check_recommendation_rate_limit();

-- ─── Profiles INSERT policy ────────────────────────────────────────────────
-- Allows new users to insert their own profile row during onboarding.

DROP POLICY IF EXISTS profiles_insert_self ON profiles;
CREATE POLICY profiles_insert_self ON profiles
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = id);

-- END HISTORICAL MIGRATION: 20260717000003_add_missing_triggers_and_policy.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260720000001_profile_report_count_view.sql
--
-- Profile report count view
-- Aggregates report counts per profile for public display.
-- Owned by postgres to bypass the underlying `reports` table RLS.
-- Only the aggregated count is exposed — no individual report details.

CREATE OR REPLACE VIEW profile_report_stats AS
SELECT
  target_profile_id AS profile_id,
  COUNT(*) AS report_count
FROM reports
WHERE target_profile_id IS NOT NULL
GROUP BY target_profile_id;

ALTER VIEW profile_report_stats OWNER TO postgres;

GRANT SELECT ON profile_report_stats TO authenticated;

-- END HISTORICAL MIGRATION: 20260720000001_profile_report_count_view.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260720000002_add_event_registrations.sql
--
-- Event Registration System
-- Adds event_registrations table, alters events table, adds RLS, triggers, and indexes.

-- 1) Alter events table — add capacity and deadline fields
ALTER TABLE events
  ADD COLUMN IF NOT EXISTS max_capacity INT DEFAULT NULL
    CHECK (max_capacity IS NULL OR max_capacity > 0),
  ADD COLUMN IF NOT EXISTS registration_deadline TIMESTAMPTZ DEFAULT NULL;

-- 2) Create event_registrations table
CREATE TABLE IF NOT EXISTS event_registrations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id UUID NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled', 'waitlisted')),
  waitlist_position INT DEFAULT NULL,
  reviewed_by UUID REFERENCES profiles(id),
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW()),
  UNIQUE (event_id, profile_id)
);

-- 3) RLS
ALTER TABLE event_registrations ENABLE ROW LEVEL SECURITY;

-- SELECT: self + event host + admin
CREATE POLICY registrations_read_self_host_admin ON event_registrations FOR SELECT TO authenticated
USING (
  profile_id = auth.uid()
  OR EXISTS (
    SELECT 1 FROM events e
    WHERE e.id = event_id AND e.creator_id = auth.uid()
  )
  OR auth.jwt() ->> 'role' = 'admin'
);

-- INSERT: self only
CREATE POLICY registrations_insert_self ON event_registrations FOR INSERT TO authenticated
WITH CHECK (profile_id = auth.uid());

-- UPDATE: event host only (approve/reject)
CREATE POLICY registrations_update_host ON event_registrations FOR UPDATE TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM events e
    WHERE e.id = event_id AND e.creator_id = auth.uid()
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM events e
    WHERE e.id = event_id AND e.creator_id = auth.uid()
  )
);

-- DELETE: self (cancel) + event host (force cancel)
CREATE POLICY registrations_delete_self ON event_registrations FOR DELETE TO authenticated
USING (
  profile_id = auth.uid()
  OR EXISTS (
    SELECT 1 FROM events e
    WHERE e.id = event_id AND e.creator_id = auth.uid()
  )
);

-- 4) Waitlist promotion trigger
CREATE OR REPLACE FUNCTION promote_waitlist_on_cancel()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  next_waitlist RECORD;
  current_approved_count INT;
  event_max_cap INT;
BEGIN
  IF OLD.status NOT IN ('approved', 'waitlisted') OR NEW.status != 'cancelled' THEN
    RETURN NEW;
  END IF;

  SELECT max_capacity INTO event_max_cap
  FROM events WHERE id = OLD.event_id;

  SELECT COUNT(*) INTO current_approved_count
  FROM event_registrations
  WHERE event_id = OLD.event_id AND status = 'approved';

  SELECT * INTO next_waitlist
  FROM event_registrations
  WHERE event_id = OLD.event_id
    AND status = 'waitlisted'
  ORDER BY created_at ASC
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN NEW;
  END IF;

  IF event_max_cap IS NOT NULL AND current_approved_count >= event_max_cap THEN
    RETURN NEW;
  END IF;

  UPDATE event_registrations
  SET status = 'pending',
      waitlist_position = NULL
  WHERE id = next_waitlist.id;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_promote_waitlist ON event_registrations;
CREATE TRIGGER trg_promote_waitlist
AFTER UPDATE ON event_registrations
FOR EACH ROW
EXECUTE FUNCTION promote_waitlist_on_cancel();

-- 5) Indexes
CREATE INDEX IF NOT EXISTS idx_event_registrations_event_id ON event_registrations (event_id);
CREATE INDEX IF NOT EXISTS idx_event_registrations_profile_id ON event_registrations (profile_id);
CREATE INDEX IF NOT EXISTS idx_event_registrations_status ON event_registrations (event_id, status);
CREATE INDEX IF NOT EXISTS idx_event_registrations_waitlist ON event_registrations (event_id, created_at ASC)
  WHERE status = 'waitlisted';

-- END HISTORICAL MIGRATION: 20260720000002_add_event_registrations.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260720000003_add_connections_and_event_visibility.sql
--
-- Connections table & Event Visibility RLS
-- Adds connections table for bidirectional relationships,
-- replaces events_read_all with visibility-based policy.

-- 1) Create connections table
CREATE TABLE IF NOT EXISTS connections (
  requester_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  receiver_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'accepted')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW()),
  PRIMARY KEY (requester_id, receiver_id),
  CHECK (requester_id <> receiver_id)
);

-- 2) RLS for connections
ALTER TABLE connections ENABLE ROW LEVEL SECURITY;

CREATE POLICY connections_read_self ON connections FOR SELECT TO authenticated
USING (requester_id = auth.uid() OR receiver_id = auth.uid());

CREATE POLICY connections_insert_requester ON connections FOR INSERT TO authenticated
WITH CHECK (requester_id = auth.uid());

CREATE POLICY connections_update_receiver ON connections FOR UPDATE TO authenticated
USING (receiver_id = auth.uid()) WITH CHECK (receiver_id = auth.uid());

CREATE POLICY connections_delete_participant ON connections FOR DELETE TO authenticated
USING (requester_id = auth.uid() OR receiver_id = auth.uid());

-- 3) Replace events_read_all with visibility-based policy
DROP POLICY IF EXISTS events_read_all ON events;

CREATE POLICY events_read_visibility ON events FOR SELECT TO authenticated
USING (
  -- public: all authenticated users can see
  (visibility_settings ->> 'type') IS NULL
  OR (visibility_settings ->> 'type') = 'public'
  -- owner can always see own events
  OR creator_id = auth.uid()
  -- connections_only: viewer and creator have an accepted connection
  OR (
    (visibility_settings ->> 'type') = 'connections_only'
    AND EXISTS (
      SELECT 1 FROM connections c
      WHERE c.status = 'accepted'
        AND (
          (c.requester_id = auth.uid() AND c.receiver_id = events.creator_id)
          OR
          (c.requester_id = events.creator_id AND c.receiver_id = auth.uid())
        )
    )
  )
);

-- 4) Indexes
CREATE INDEX IF NOT EXISTS idx_connections_receiver_id ON connections (receiver_id);
CREATE INDEX IF NOT EXISTS idx_connections_requester_id ON connections (requester_id);

-- END HISTORICAL MIGRATION: 20260720000003_add_connections_and_event_visibility.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260721000001_add_cancellation_pending_status.sql
--
ALTER TABLE "public"."event_registrations"
DROP CONSTRAINT "event_registrations_status_check";

ALTER TABLE "public"."event_registrations"
ADD CONSTRAINT "event_registrations_status_check"
CHECK (("status" = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'cancelled'::text, 'waitlisted'::text, 'cancellation_pending'::text])));

-- END HISTORICAL MIGRATION: 20260721000001_add_cancellation_pending_status.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260721000002_add_cancellation_rejected_status.sql
--
ALTER TABLE "public"."event_registrations"
DROP CONSTRAINT "event_registrations_status_check";

ALTER TABLE "public"."event_registrations"
ADD CONSTRAINT "event_registrations_status_check"
CHECK (("status" = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'cancelled'::text, 'waitlisted'::text, 'cancellation_pending'::text, 'cancellation_rejected'::text])));

-- END HISTORICAL MIGRATION: 20260721000002_add_cancellation_rejected_status.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260721000003_add_cancellation_rejected_status.sql
--
-- Remove the old unique constraint
ALTER TABLE "public"."event_registrations"
DROP CONSTRAINT IF EXISTS "event_registrations_event_id_profile_id_key";

-- Create a partial unique index that only enforces uniqueness for non-cancelled registrations
CREATE UNIQUE INDEX IF NOT EXISTS "unique_active_registration"
ON "public"."event_registrations" ("event_id", "profile_id")
WHERE "status" != 'cancelled';

-- Update status check constraint
ALTER TABLE "public"."event_registrations"
DROP CONSTRAINT IF EXISTS "event_registrations_status_check";

ALTER TABLE "public"."event_registrations"
ADD CONSTRAINT "event_registrations_status_check"
CHECK (("status" = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'cancelled'::text, 'waitlisted'::text, 'cancellation_pending'::text, 'cancellation_rejected'::text])));

-- END HISTORICAL MIGRATION: 20260721000003_add_cancellation_rejected_status.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260724050011_create_ai_characters_table.sql
--
-- Create the ai_characters table
create table public.ai_characters (
  id uuid not null default gen_random_uuid (),
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  persona text not null,
  created_at timestamp with time zone not null default now(),
  constraint ai_characters_pkey primary key (id)
);

-- Enable Row Level Security
alter table public.ai_characters enable row level security;

-- RLS Policies

-- Policy for SELECT: Users can view their own AI characters
create policy "Users can view their own AI characters"
  on public.ai_characters
  for select
  to authenticated
  using ( (select auth.uid()) = user_id );

-- Policy for INSERT: Users can insert their own AI characters
create policy "Users can insert their own AI characters"
  on public.ai_characters
  for insert
  to authenticated
  with check ( (select auth.uid()) = user_id );

-- Policy for UPDATE: Users can update their own AI characters
create policy "Users can update their own AI characters"
  on public.ai_characters
  for update
  to authenticated
  using ( (select auth.uid()) = user_id )
  with check ( (select auth.uid()) = user_id );

-- Policy for DELETE: Users can delete their own AI characters
create policy "Users can delete their own AI characters"
  on public.ai_characters
  for delete
  to authenticated
  using ( (select auth.uid()) = user_id );

-- END HISTORICAL MIGRATION: 20260724050011_create_ai_characters_table.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260724050012_create_ai_chats_table.sql
--
-- Create the ai_chats table
create table public.ai_chats (
  id uuid not null default gen_random_uuid (),
  character_id uuid not null references public.ai_characters (id) on delete cascade,
  messages jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone not null default now(),
  constraint ai_chats_pkey primary key (id)
);

-- Enable Row Level Security
alter table public.ai_chats enable row level security;

-- RLS Policies

-- Policy for SELECT: Users can view their own AI chats
create policy "Users can view their own AI chats"
  on public.ai_chats
  for select
  to authenticated
  using (
    exists (
      select 1 from public.ai_characters
      where ai_characters.id = ai_chats.character_id
      and ai_characters.user_id = auth.uid()
    )
  );

-- Policy for INSERT: Users can insert their own AI chats
create policy "Users can insert their own AI chats"
  on public.ai_chats
  for insert
  to authenticated
  with check (
    exists (
      select 1 from public.ai_characters
      where ai_characters.id = ai_chats.character_id
      and ai_characters.user_id = auth.uid()
    )
  );

-- END HISTORICAL MIGRATION: 20260724050012_create_ai_chats_table.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260724050013_add_memory_and_session.sql
--
-- Add memory column to ai_characters for conversation summaries (max 500 chars)
alter table public.ai_characters add column if not exists memory text check (char_length(memory) <= 500);

-- Add session_id to ai_chats to support multiple conversation sessions
alter table public.ai_chats add column if not exists session_id uuid not null default gen_random_uuid();

-- END HISTORICAL MIGRATION: 20260724050013_add_memory_and_session.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260724050014_create_ai_chat_feedback_table.sql
--
-- Create the ai_chat_feedback table for storing like/dislike on AI responses
-- Each click inserts a new row (no UNIQUE constraint — users can record feedback many times)
create table public.ai_chat_feedback (
  id uuid not null default gen_random_uuid (),
  character_id uuid not null references public.ai_characters (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  model_name text not null,
  feedback text not null check (feedback in ('like', 'dislike')),
  created_at timestamp with time zone not null default now(),
  constraint ai_chat_feedback_pkey primary key (id)
);

-- Enable Row Level Security
alter table public.ai_chat_feedback enable row level security;

-- RLS Policies

-- Policy for SELECT: Users can view their own feedback
create policy "Users can view their own feedback"
  on public.ai_chat_feedback
  for select
  to authenticated
  using (user_id = auth.uid());

-- Policy for INSERT: Users can insert their own feedback
create policy "Users can insert their own feedback"
  on public.ai_chat_feedback
  for insert
  to authenticated
  with check (user_id = auth.uid());

-- END HISTORICAL MIGRATION: 20260724050014_create_ai_chat_feedback_table.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260724050015_create_ai_conversations_and_messages.sql
--
-- ai_conversations: 代表一場獨立對話
CREATE TABLE IF NOT EXISTS public.ai_conversations (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  character_id UUID NOT NULL REFERENCES public.ai_characters(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ai_conversations_pkey PRIMARY KEY (id)
);

-- ai_messages: 對話中的單一則訊息
CREATE TABLE IF NOT EXISTS public.ai_messages (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL REFERENCES public.ai_conversations(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ai_messages_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_ai_messages_conversation_id
  ON ai_messages (conversation_id, created_at ASC);

-- 遷移現有 ai_chats 資料到新結構
-- 每筆 character 的最新 row 視為一組完整對話
DO $$
DECLARE
  char_record RECORD;
  latest_chat RECORD;
  new_conv_id UUID;
  msg_item RECORD;
BEGIN
  FOR char_record IN SELECT DISTINCT character_id FROM public.ai_chats LOOP
    -- 取該 character 最新的一筆 row（包含完整對話）
    SELECT id, messages, created_at INTO latest_chat
    FROM public.ai_chats
    WHERE character_id = char_record.character_id
    ORDER BY created_at DESC
    LIMIT 1;

    -- 建立 conversation
    INSERT INTO public.ai_conversations (character_id, created_at)
    VALUES (char_record.character_id, latest_chat.created_at)
    RETURNING id INTO new_conv_id;

    -- 逐筆訊息插入 ai_messages
    FOR msg_item IN SELECT * FROM jsonb_to_recordset(latest_chat.messages) AS x(role text, content text)
    LOOP
      INSERT INTO public.ai_messages (conversation_id, role, content, created_at)
      VALUES (new_conv_id, msg_item.role, msg_item.content, latest_chat.created_at);
    END LOOP;
  END LOOP;
END $$;

-- 刪除舊表
DROP TABLE IF EXISTS public.ai_chats;

-- RLS
ALTER TABLE public.ai_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_messages ENABLE ROW LEVEL SECURITY;

-- ai_conversations RLS
CREATE POLICY ai_conversations_select_owner ON public.ai_conversations FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.ai_characters ac
      WHERE ac.id = character_id AND ac.user_id = auth.uid()
    )
  );

CREATE POLICY ai_conversations_insert_owner ON public.ai_conversations FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.ai_characters ac
      WHERE ac.id = character_id AND ac.user_id = auth.uid()
    )
  );

CREATE POLICY ai_conversations_delete_owner ON public.ai_conversations FOR DELETE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.ai_characters ac
      WHERE ac.id = character_id AND ac.user_id = auth.uid()
    )
  );

-- ai_messages RLS（透過 conversation 連到 character 再連到 user）
CREATE POLICY ai_messages_select_owner ON public.ai_messages FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.ai_conversations acv
      JOIN public.ai_characters ac ON ac.id = acv.character_id
      WHERE acv.id = conversation_id AND ac.user_id = auth.uid()
    )
  );

CREATE POLICY ai_messages_insert_owner ON public.ai_messages FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.ai_conversations acv
      JOIN public.ai_characters ac ON ac.id = acv.character_id
      WHERE acv.id = conversation_id AND ac.user_id = auth.uid()
    )
  );

CREATE POLICY ai_messages_delete_owner ON public.ai_messages FOR DELETE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.ai_conversations acv
      JOIN public.ai_characters ac ON ac.id = acv.character_id
      WHERE acv.id = conversation_id AND ac.user_id = auth.uid()
    )
  );

-- END HISTORICAL MIGRATION: 20260724050015_create_ai_conversations_and_messages.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260724050016_drop_ai_chat_feedback_unique.sql
--
-- Drop the UNIQUE constraint on (character_id, user_id) to allow multiple feedback entries
alter table public.ai_chat_feedback drop constraint if exists ai_chat_feedback_character_user_unique;

-- Drop the updated_at column and trigger since we no longer UPDATE rows
drop trigger if exists trg_ai_chat_feedback_updated_at on public.ai_chat_feedback;
drop function if exists public.update_ai_chat_feedback_updated_at;
alter table public.ai_chat_feedback drop column if exists updated_at;

-- Drop the UPDATE policy since we only INSERT new rows
drop policy if exists "Users can update their own feedback" on public.ai_chat_feedback;

-- END HISTORICAL MIGRATION: 20260724050016_drop_ai_chat_feedback_unique.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260729000001_add_taiwan_region_to_events.sql
--
-- Create taiwan_region enum type for event location filtering
-- 大分區模式：北中南東離島 + 線上，避免單一縣市活動過少造成空搜尋
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'taiwan_region') THEN
        CREATE TYPE public.taiwan_region AS ENUM (
            'North',
            'Central',
            'South',
            'East',
            'Islands',
            'Online'
        );
    END IF;
END $$;

-- Add location columns to events table
alter table public.events
  add column if not exists location_region public.taiwan_region,
  add column if not exists location_detail text;

-- location_region is required for new events, but existing rows get null
-- (enforced at the application layer for now)

-- END HISTORICAL MIGRATION: 20260729000001_add_taiwan_region_to_events.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260729000002_add_role_status_audit_trigger.sql
--
-- Audit Trigger for role_status changes on profiles
--
-- Logs any role_status change to the audit_logs table.
-- When auth.uid() is available (authenticated session), it's recorded as actor_id.
-- When auth.uid() is null (service_role operations like admin-role-upgrade edge function),
-- the edge function handles audit logging separately, so trigger skips to avoid duplication.
--
-- This covers: user self-updates (REST API) and any direct DB changes.

CREATE OR REPLACE FUNCTION log_role_status_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Only log when role_status actually changes AND we have an authenticated user
  -- (service_role operations log via edge function, not here)
  IF OLD.role_status IS DISTINCT FROM NEW.role_status AND auth.uid() IS NOT NULL THEN
    INSERT INTO audit_logs (actor_id, target_profile_id, action, payload)
    VALUES (
      auth.uid(),
      NEW.id,
      'role_status_change',
      jsonb_build_object(
        'old_status', OLD.role_status,
        'new_status', NEW.role_status
      )
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_log_role_status_change ON profiles;
CREATE TRIGGER trg_log_role_status_change
AFTER UPDATE ON profiles
FOR EACH ROW
EXECUTE FUNCTION log_role_status_change();

-- END HISTORICAL MIGRATION: 20260729000002_add_role_status_audit_trigger.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260729000003_add_storage_buckets_and_rls.sql
--
-- Supabase Storage buckets for user-uploaded content
--
-- Creates two buckets:
--   - avatars: user profile pictures
--   - event-covers: event cover images
--
-- RLS policies:
--   - Public read (SELECT) for authenticated users
--   - Owner-only write (INSERT/UPDATE/DELETE) for file owners
--
-- See: docs/spec/007-asset-storage-spec.md

-- ============================================================
-- Helper: insert policy for a bucket (owner-only write)
-- ============================================================
-- Note: Storage RLS policies use the `storage` schema and the
-- `bucket_id` column on `storage.objects` table.

-- ============================================================
-- 1) avatars bucket
-- ============================================================
INSERT INTO storage.buckets (id, name, public, avif_autodetection, file_size_limit, allowed_mime_types)
VALUES ('avatars', 'avatars', true, false, 5242880, ARRAY['image/png', 'image/jpeg', 'image/webp', 'image/gif'])
ON CONFLICT (id) DO NOTHING;

-- Allow authenticated users to read any avatar
DROP POLICY IF EXISTS avatars_select_auth ON storage.objects;
CREATE POLICY avatars_select_auth ON storage.objects
  FOR SELECT TO authenticated
  USING (bucket_id = 'avatars');

-- Allow authenticated users to insert their own avatar
DROP POLICY IF EXISTS avatars_insert_owner ON storage.objects;
CREATE POLICY avatars_insert_owner ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Allow owner to update their avatar
DROP POLICY IF EXISTS avatars_update_owner ON storage.objects;
CREATE POLICY avatars_update_owner ON storage.objects
  FOR UPDATE TO authenticated
  USING (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = auth.uid()::text
  )
  WITH CHECK (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Allow owner to delete their avatar
DROP POLICY IF EXISTS avatars_delete_owner ON storage.objects;
CREATE POLICY avatars_delete_owner ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- ============================================================
-- 2) event-covers bucket
-- ============================================================
INSERT INTO storage.buckets (id, name, public, avif_autodetection, file_size_limit, allowed_mime_types)
VALUES ('event-covers', 'event-covers', true, false, 10485760, ARRAY['image/png', 'image/jpeg', 'image/webp'])
ON CONFLICT (id) DO NOTHING;

-- Allow authenticated users to read any event cover
DROP POLICY IF EXISTS event_covers_select_auth ON storage.objects;
CREATE POLICY event_covers_select_auth ON storage.objects
  FOR SELECT TO authenticated
  USING (bucket_id = 'event-covers');

-- Allow authenticated users to insert their own event cover
DROP POLICY IF EXISTS event_covers_insert_owner ON storage.objects;
CREATE POLICY event_covers_insert_owner ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'event-covers'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Allow owner to update their event cover
DROP POLICY IF EXISTS event_covers_update_owner ON storage.objects;
CREATE POLICY event_covers_update_owner ON storage.objects
  FOR UPDATE TO authenticated
  USING (
    bucket_id = 'event-covers'
    AND (storage.foldername(name))[1] = auth.uid()::text
  )
  WITH CHECK (
    bucket_id = 'event-covers'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Allow owner to delete their event cover
DROP POLICY IF EXISTS event_covers_delete_owner ON storage.objects;
CREATE POLICY event_covers_delete_owner ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'event-covers'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- END HISTORICAL MIGRATION: 20260729000003_add_storage_buckets_and_rls.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260729000004_add_audit_logs_self_select.sql
--
-- Allow users to SELECT their own audit_logs entries
--
-- By default, audit_logs is admin-only (for both SELECT and INSERT).
-- This policy lets general users see entries where they are the target,
-- giving them visibility into admin actions that affect their account
-- (e.g., role upgrades, moderation actions).
--
-- Security: users can only see rows where target_profile_id = auth.uid(),
-- and cannot modify audit_logs in any way.

DROP POLICY IF EXISTS audit_logs_self_select ON audit_logs;
CREATE POLICY audit_logs_self_select ON audit_logs
  FOR SELECT TO authenticated
  USING (
    target_profile_id = auth.uid()
  );

-- Note: The existing audit_logs_admin_read policy remains in place
-- for admin users who can see ALL audit logs.
-- The system_insert policy also remains for service_role writes.

-- END HISTORICAL MIGRATION: 20260729000004_add_audit_logs_self_select.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260803000001_add_category_forms_recurrence.sql
--
-- Migration: Add category, registration_form_config, recurrence_rule, series_id to events
-- Create event_registration_responses table with RLS isolation
-- Date: 2026-08-03

-- 1. Add new columns to events table
ALTER TABLE events
  ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'Social'
    CHECK (category IN ('Social', 'Practice')),
  ADD COLUMN IF NOT EXISTS registration_form_config JSONB DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS recurrence_rule JSONB DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS series_id UUID DEFAULT NULL;

-- 2. Create event_registration_responses table for RLS-isolated form responses
CREATE TABLE IF NOT EXISTS event_registration_responses (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  registration_id UUID NOT NULL REFERENCES event_registrations(id) ON DELETE CASCADE,
  responses JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW()),
  UNIQUE (registration_id)
);

-- 3. Enable RLS on new table
ALTER TABLE event_registration_responses ENABLE ROW LEVEL SECURITY;

-- 4. RLS for event_registration_responses:
--    SELECT: only the registrant, event host, or admin
CREATE POLICY reg_responses_read_self_host_admin ON event_registration_responses FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM event_registrations er
    WHERE er.id = registration_id
      AND (
        er.profile_id = auth.uid()
        OR EXISTS (
          SELECT 1 FROM events e
          WHERE e.id = er.event_id AND e.creator_id = auth.uid()
        )
      )
  )
  OR auth.jwt() ->> 'role' = 'admin'
);

--    INSERT: only via service role (Edge Functions bypass RLS)
CREATE POLICY reg_responses_service_insert ON event_registration_responses FOR INSERT TO authenticated
WITH CHECK (auth.jwt() ->> 'role' = 'service_role');

--    UPDATE: only via service role
CREATE POLICY reg_responses_service_update ON event_registration_responses FOR UPDATE TO authenticated
USING (auth.jwt() ->> 'role' = 'service_role')
WITH CHECK (auth.jwt() ->> 'role' = 'service_role');

-- 5. New indexes for category filtering and series lookups
CREATE INDEX IF NOT EXISTS idx_events_category ON events (category);
CREATE INDEX IF NOT EXISTS idx_events_series_id ON events (series_id) WHERE series_id IS NOT NULL;

-- END HISTORICAL MIGRATION: 20260803000001_add_category_forms_recurrence.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260805000001_add_registration_checkin.sql
--
-- Migration: 20260805000001_add_registration_checkin.sql
-- 1. 為 event_registrations 新增 checked_in_at 欄位，記錄實際出席簽到時間
-- 2. 新增 waitlist_converted_at 欄位，記錄候補轉化時間（供 get-user-analytics 統計）
-- 3. 更新 promote_waitlist_on_cancel trigger 以設定 waitlist_converted_at
-- 4. 新增主辦人簽到 RLS 政策

-- ============================================================
-- Step 1: Add checked_in_at column
-- ============================================================
ALTER TABLE event_registrations
ADD COLUMN IF NOT EXISTS checked_in_at TIMESTAMPTZ;

COMMENT ON COLUMN event_registrations.checked_in_at IS '實際出席簽到時間戳，NULL 表示尚未簽到。僅 status = approved 的報名可被簽到。';

-- ============================================================
-- Step 2: Add waitlist_converted_at column
-- ============================================================
-- 供 get-user-analytics 統計「候補轉化數」使用。
-- 當候補者被自動遞補為 pending 時，由 trigger 填入時間戳。
ALTER TABLE event_registrations
ADD COLUMN IF NOT EXISTS waitlist_converted_at TIMESTAMPTZ;

COMMENT ON COLUMN event_registrations.waitlist_converted_at IS '候補轉化時間戳。當 waitlisted 記錄被 promote 為 pending 時，由 trigger 填入。NULL 表示未曾從候補轉化。';

-- ============================================================
-- Step 3: Update promote trigger to set waitlist_converted_at
-- ============================================================
CREATE OR REPLACE FUNCTION promote_waitlist_on_cancel()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  next_waitlist RECORD;
  current_approved_count INT;
  event_max_cap INT;
BEGIN
  IF OLD.status NOT IN ('approved', 'waitlisted') OR NEW.status != 'cancelled' THEN
    RETURN NEW;
  END IF;

  SELECT max_capacity INTO event_max_cap
  FROM events WHERE id = OLD.event_id;

  SELECT COUNT(*) INTO current_approved_count
  FROM event_registrations
  WHERE event_id = OLD.event_id AND status = 'approved';

  SELECT * INTO next_waitlist
  FROM event_registrations
  WHERE event_id = OLD.event_id
    AND status = 'waitlisted'
  ORDER BY created_at ASC
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN NEW;
  END IF;

  IF event_max_cap IS NOT NULL AND current_approved_count >= event_max_cap THEN
    RETURN NEW;
  END IF;

  UPDATE event_registrations
  SET status = 'pending',
      waitlist_position = NULL,
      waitlist_converted_at = TIMEZONE('utc', NOW())
  WHERE id = next_waitlist.id;

  RETURN NEW;
END;
$$;

-- ============================================================
-- Step 4: Add explicit check-in RLS policy for event hosts
-- ============================================================
CREATE POLICY registrations_checkin_host
  ON event_registrations
  FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM events e
      WHERE e.id = event_id AND e.creator_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM events e
      WHERE e.id = event_id AND e.creator_id = auth.uid()
    )
  );

-- END HISTORICAL MIGRATION: 20260805000001_add_registration_checkin.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260807000001_apply_remote_schema_drift.sql
--
-- Extracted from the remote schema pull on 2026-08-07.
-- Keep only the actual schema drift that is not already owned by earlier migrations.

ALTER TABLE "public"."profiles"
  DROP CONSTRAINT IF EXISTS "profiles_social_links_min_one";

ALTER TABLE "public"."profiles"
  DROP CONSTRAINT IF EXISTS "profiles_role_status_check";

ALTER TABLE "public"."profiles"
  ADD CONSTRAINT "profiles_role_status_check"
  CHECK ((role_status = ANY (ARRAY['general'::text, 'venue_pending'::text, 'venue_approved'::text, 'admin'::text]))) NOT VALID;

ALTER TABLE "public"."profiles"
  VALIDATE CONSTRAINT "profiles_role_status_check";

ALTER TABLE "public"."ai_conversations"
  ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE "public"."issue_comments"
  ALTER COLUMN "id" SET DEFAULT gen_random_uuid();

ALTER TABLE "public"."issues"
  ALTER COLUMN "id" SET DEFAULT gen_random_uuid();

-- END HISTORICAL MIGRATION: 20260807000001_apply_remote_schema_drift.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260810000001_restrict_draft_event_visibility.sql
--
-- Draft events are private to their creator regardless of visibility_settings.
DROP POLICY IF EXISTS events_read_visibility ON events;

CREATE POLICY events_read_visibility ON events FOR SELECT TO authenticated
USING (
  creator_id = auth.uid()
  OR (
    lifecycle_status <> 'draft'
    AND (
      (visibility_settings ->> 'type') IS NULL
      OR (visibility_settings ->> 'type') = 'public'
      OR (
        (visibility_settings ->> 'type') = 'connections_only'
        AND EXISTS (
          SELECT 1 FROM connections c
          WHERE c.status = 'accepted'
            AND (
              (c.requester_id = auth.uid() AND c.receiver_id = events.creator_id)
              OR
              (c.requester_id = events.creator_id AND c.receiver_id = auth.uid())
            )
        )
      )
    )
  )
);

-- END HISTORICAL MIGRATION: 20260810000001_restrict_draft_event_visibility.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260810000002_add_event_publication_control.sql
--
-- Event publication control is separate from lifecycle_status.
-- The initial events table predates lifecycle_status. Preserve existing events
-- as published, then make newly created events drafts by default.
ALTER TABLE public.events
  ADD COLUMN IF NOT EXISTS lifecycle_status TEXT NOT NULL DEFAULT 'published';

ALTER TABLE public.events
  DROP CONSTRAINT IF EXISTS events_lifecycle_status_check,
  ADD CONSTRAINT events_lifecycle_status_check
    CHECK (lifecycle_status IN (
      'draft',
      'published',
      'registration_open',
      'registration_closed',
      'completed',
      'archived',
      'cancelled'
    ));

ALTER TABLE public.events
  ALTER COLUMN lifecycle_status SET DEFAULT 'draft';

ALTER TABLE public.events
  ADD COLUMN IF NOT EXISTS publication_status TEXT NOT NULL DEFAULT 'closed',
  ADD COLUMN IF NOT EXISTS publish_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS unpublish_at TIMESTAMPTZ;

UPDATE public.events
SET publication_status = CASE
  WHEN lifecycle_status = 'draft' THEN 'closed'
  ELSE 'published'
END
WHERE publication_status = 'closed';

ALTER TABLE public.events
  DROP CONSTRAINT IF EXISTS events_publication_status_check,
  ADD CONSTRAINT events_publication_status_check
    CHECK (publication_status IN ('published', 'closed')),
  DROP CONSTRAINT IF EXISTS events_publication_schedule_order,
  ADD CONSTRAINT events_publication_schedule_order
    CHECK (publish_at IS NULL OR unpublish_at IS NULL OR publish_at < unpublish_at);

CREATE INDEX IF NOT EXISTS idx_events_publication_schedule
  ON public.events (publication_status, publish_at, unpublish_at);

CREATE OR REPLACE FUNCTION public.prevent_direct_event_publication_update()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF (OLD.publication_status, OLD.publish_at, OLD.unpublish_at)
     IS DISTINCT FROM (NEW.publication_status, NEW.publish_at, NEW.unpublish_at)
    AND COALESCE(current_setting('app.event_publication_rpc', true), '') <> 'on'
  THEN
    RAISE EXCEPTION 'event publication must be changed through set_event_publication';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_prevent_direct_event_publication_update ON public.events;
CREATE TRIGGER trg_prevent_direct_event_publication_update
BEFORE UPDATE ON public.events
FOR EACH ROW
EXECUTE FUNCTION public.prevent_direct_event_publication_update();

CREATE OR REPLACE FUNCTION public.set_event_publication(
  p_event_id UUID,
  p_publication_status TEXT,
  p_publish_at TIMESTAMPTZ DEFAULT NULL,
  p_unpublish_at TIMESTAMPTZ DEFAULT NULL
)
RETURNS public.events
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  event_row public.events;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'authentication required';
  END IF;

  IF p_publication_status NOT IN ('published', 'closed') THEN
    RAISE EXCEPTION 'invalid publication status';
  END IF;

  IF p_publish_at IS NOT NULL AND p_unpublish_at IS NOT NULL
    AND p_publish_at >= p_unpublish_at
  THEN
    RAISE EXCEPTION 'publish_at must be before unpublish_at';
  END IF;

  PERFORM set_config('app.event_publication_rpc', 'on', true);

  UPDATE public.events
  SET publication_status = p_publication_status,
      lifecycle_status = CASE
        WHEN lifecycle_status = 'draft' AND p_publication_status = 'published' THEN 'published'
        ELSE lifecycle_status
      END,
      publish_at = p_publish_at,
      unpublish_at = p_unpublish_at,
      updated_at = timezone('utc', now())
  WHERE id = p_event_id
    AND creator_id = auth.uid()
  RETURNING * INTO event_row;

  IF event_row.id IS NULL THEN
    RAISE EXCEPTION 'event not found or publication transition is not allowed';
  END IF;

  RETURN event_row;
END;
$$;

REVOKE ALL ON FUNCTION public.set_event_publication(UUID, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.set_event_publication(UUID, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) TO authenticated;

CREATE OR REPLACE FUNCTION public.apply_due_event_publication_schedules()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  changed_count INTEGER;
BEGIN
  PERFORM set_config('app.event_publication_rpc', 'on', true);

  UPDATE public.events
  SET publication_status = CASE
        WHEN unpublish_at IS NOT NULL AND unpublish_at <= timezone('utc', now()) THEN 'closed'
        WHEN publish_at IS NOT NULL AND publish_at <= timezone('utc', now())
          AND lifecycle_status <> 'draft' THEN 'published'
        ELSE publication_status
      END,
      publish_at = CASE
        WHEN publish_at IS NOT NULL AND publish_at <= timezone('utc', now()) THEN NULL
        ELSE publish_at
      END,
      unpublish_at = CASE
        WHEN unpublish_at IS NOT NULL AND unpublish_at <= timezone('utc', now()) THEN NULL
        ELSE unpublish_at
      END,
      updated_at = timezone('utc', now())
  WHERE (publish_at IS NOT NULL AND publish_at <= timezone('utc', now()) AND lifecycle_status <> 'draft')
     OR (unpublish_at IS NOT NULL AND unpublish_at <= timezone('utc', now()));

  GET DIAGNOSTICS changed_count = ROW_COUNT;
  RETURN changed_count;
END;
$$;

REVOKE ALL ON FUNCTION public.apply_due_event_publication_schedules() FROM PUBLIC;

DROP POLICY IF EXISTS events_read_visibility ON public.events;
CREATE POLICY events_read_visibility ON public.events FOR SELECT TO authenticated
USING (
  creator_id = auth.uid()
  OR (
    lifecycle_status <> 'draft'
    AND publication_status = 'published'
    AND (
      (visibility_settings ->> 'type') IS NULL
      OR (visibility_settings ->> 'type') = 'public'
      OR (
        (visibility_settings ->> 'type') = 'connections_only'
        AND EXISTS (
          SELECT 1 FROM public.connections c
          WHERE c.status = 'accepted'
            AND ((c.requester_id = auth.uid() AND c.receiver_id = events.creator_id)
              OR (c.requester_id = events.creator_id AND c.receiver_id = auth.uid()))
        )
      )
    )
  )
);

CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA extensions;
SELECT cron.unschedule('apply-due-event-publication-schedules')
WHERE EXISTS (
  SELECT 1 FROM cron.job WHERE jobname = 'apply-due-event-publication-schedules'
);
SELECT cron.schedule(
  'apply-due-event-publication-schedules',
  '* * * * *',
  $$SELECT public.apply_due_event_publication_schedules();$$
);

-- END HISTORICAL MIGRATION: 20260810000002_add_event_publication_control.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260810000003_add_event_notification_subscriptions.sql
--
-- Activity notifications: subscriptions by event type or creator.
-- Existing events are intentionally not backfilled; only future publication
-- transitions create notifications.

CREATE TABLE IF NOT EXISTS public.event_notification_subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  event_type TEXT,
  creator_profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT event_notification_subscriptions_one_target
    CHECK ((event_type IS NOT NULL) <> (creator_profile_id IS NOT NULL)),
  CONSTRAINT event_notification_subscriptions_event_type_check
    CHECK (event_type IS NULL OR event_type IN (
      'Bondage', 'Discipline', 'Dominance / Submission', 'D/S',
      'Sadism / Masochism', 'SM', 'SP', 'Spanking', 'TK', 'Tickling',
      'K9', 'DID', 'CNC', 'DDLG', '4 love', 'ABDL',
      'Dining', 'BBQ', 'Karaoke', 'Movie', 'BoardGame', 'Travel',
      'BookClub', 'Conversation', 'SpeedDating', 'HangOut'
    )),
  CONSTRAINT event_notification_subscriptions_not_self
    CHECK (creator_profile_id IS NULL OR creator_profile_id <> profile_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_event_notification_subscriptions_type
  ON public.event_notification_subscriptions (profile_id, event_type)
  WHERE event_type IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_event_notification_subscriptions_creator
  ON public.event_notification_subscriptions (profile_id, creator_profile_id)
  WHERE creator_profile_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_event_notification_subscriptions_event_type
  ON public.event_notification_subscriptions (event_type, profile_id)
  WHERE event_type IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  recipient_profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  notification_type TEXT NOT NULL
    CHECK (notification_type IN ('new_event')),
  event_id UUID NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  UNIQUE (recipient_profile_id, notification_type, event_id)
);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient_created_at
  ON public.notifications (recipient_profile_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_notifications_unread
  ON public.notifications (recipient_profile_id, created_at DESC)
  WHERE read_at IS NULL;

ALTER TABLE public.event_notification_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS event_notification_subscriptions_select_self
  ON public.event_notification_subscriptions;
CREATE POLICY event_notification_subscriptions_select_self
  ON public.event_notification_subscriptions FOR SELECT TO authenticated
  USING (profile_id = auth.uid());

DROP POLICY IF EXISTS event_notification_subscriptions_insert_self
  ON public.event_notification_subscriptions;
CREATE POLICY event_notification_subscriptions_insert_self
  ON public.event_notification_subscriptions FOR INSERT TO authenticated
  WITH CHECK (
    (
      profile_id = auth.uid()
      AND creator_profile_id IS NULL
    ) OR (
      profile_id = auth.uid()
      AND creator_profile_id IS NOT NULL
      AND creator_profile_id <> auth.uid()
      AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = creator_profile_id)
    )
  );

DROP POLICY IF EXISTS event_notification_subscriptions_delete_self
  ON public.event_notification_subscriptions;
CREATE POLICY event_notification_subscriptions_delete_self
  ON public.event_notification_subscriptions FOR DELETE TO authenticated
  USING (profile_id = auth.uid());

DROP POLICY IF EXISTS notifications_select_recipient
  ON public.notifications;
CREATE POLICY notifications_select_recipient
  ON public.notifications FOR SELECT TO authenticated
  USING (recipient_profile_id = auth.uid());

DROP POLICY IF EXISTS notifications_update_read_at
  ON public.notifications;
CREATE POLICY notifications_update_read_at
  ON public.notifications FOR UPDATE TO authenticated
  USING (recipient_profile_id = auth.uid())
  WITH CHECK (recipient_profile_id = auth.uid());

-- Browser clients may only update the read marker, never notification content
-- or recipient ownership.
REVOKE UPDATE ON public.notifications FROM authenticated;
GRANT UPDATE (read_at) ON public.notifications TO authenticated;

CREATE OR REPLACE FUNCTION public.notify_subscribers_on_event_publication()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
BEGIN
  IF OLD.publication_status = 'published'
     OR NEW.publication_status <> 'published'
     OR (NEW.visibility_settings ->> 'type') = 'private'
  THEN
    RETURN NEW;
  END IF;

  INSERT INTO public.notifications (
    recipient_profile_id,
    notification_type,
    event_id,
    title
  )
  SELECT DISTINCT s.profile_id, 'new_event', NEW.id, NEW.title
  FROM public.event_notification_subscriptions s
  WHERE s.profile_id <> NEW.creator_id
    AND (
      s.creator_profile_id = NEW.creator_id
      OR s.event_type = NEW.event_type
    )
    AND NOT EXISTS (
      SELECT 1
      FROM public.blocks b
      WHERE (b.blocker_id = s.profile_id AND b.blocked_id = NEW.creator_id)
         OR (b.blocker_id = NEW.creator_id AND b.blocked_id = s.profile_id)
    )
    AND (
      COALESCE(NEW.visibility_settings ->> 'type', 'public') = 'public'
      OR (
        NEW.visibility_settings ->> 'type' = 'connections_only'
        AND EXISTS (
          SELECT 1
          FROM public.connections c
          WHERE c.status = 'accepted'
            AND (
              (c.requester_id = s.profile_id AND c.receiver_id = NEW.creator_id)
              OR (c.requester_id = NEW.creator_id AND c.receiver_id = s.profile_id)
            )
        )
      )
    )
  ON CONFLICT (recipient_profile_id, notification_type, event_id) DO NOTHING;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_subscribers_on_event_publication ON public.events;
CREATE TRIGGER trg_notify_subscribers_on_event_publication
AFTER UPDATE OF publication_status ON public.events
FOR EACH ROW
WHEN (OLD.publication_status IS DISTINCT FROM NEW.publication_status)
EXECUTE FUNCTION public.notify_subscribers_on_event_publication();

-- END HISTORICAL MIGRATION: 20260810000003_add_event_notification_subscriptions.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260810000004_create_user_llm_api_keys.sql
--
CREATE TABLE IF NOT EXISTS public.user_llm_api_keys (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  provider TEXT NOT NULL DEFAULT 'openrouter' CHECK (provider = 'openrouter'),
  provider_key_hash TEXT NOT NULL UNIQUE,
  encrypted_key TEXT NOT NULL,
  key_version INTEGER NOT NULL DEFAULT 1 CHECK (key_version > 0),
  limit_usd NUMERIC(12, 6),
  limit_reset TEXT CHECK (limit_reset IN ('daily', 'weekly', 'monthly')),
  disabled BOOLEAN NOT NULL DEFAULT false,
  usage_usd NUMERIC(12, 6),
  limit_remaining_usd NUMERIC(12, 6),
  provider_created_at TIMESTAMPTZ,
  provider_updated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.user_llm_api_keys ENABLE ROW LEVEL SECURITY;

-- The table is intentionally server-only. No Data API role receives access,
-- because even encrypted provider credentials are not client-readable.
REVOKE ALL ON public.user_llm_api_keys FROM anon, authenticated;

CREATE INDEX IF NOT EXISTS idx_user_llm_api_keys_user_id
  ON public.user_llm_api_keys (user_id);

-- END HISTORICAL MIGRATION: 20260810000004_create_user_llm_api_keys.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260810000005_create_user_follows.sql
--
-- User following: one-way relationship, separate from bidirectional connections.
CREATE TABLE IF NOT EXISTS public.user_follows (
  follower_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  followed_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  PRIMARY KEY (follower_id, followed_id),
  CHECK (follower_id <> followed_id)
);

ALTER TABLE public.user_follows ENABLE ROW LEVEL SECURITY;

CREATE POLICY user_follows_select_participant ON public.user_follows
  FOR SELECT TO authenticated
  USING (follower_id = (select auth.uid()) OR followed_id = (select auth.uid()));

CREATE POLICY user_follows_insert_self ON public.user_follows
  FOR INSERT TO authenticated
  WITH CHECK (
    follower_id = (select auth.uid())
    AND follower_id <> followed_id
  );

CREATE POLICY user_follows_delete_self ON public.user_follows
  FOR DELETE TO authenticated
  USING (follower_id = (select auth.uid()));

CREATE INDEX IF NOT EXISTS idx_user_follows_followed_id
  ON public.user_follows (followed_id);
CREATE INDEX IF NOT EXISTS idx_user_follows_follower_id
  ON public.user_follows (follower_id);

-- END HISTORICAL MIGRATION: 20260810000005_create_user_follows.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260810061600_admin_privacy_boundary.sql
--
-- Admin JWT is not a private-data read exception.
-- PostgreSQL owner/service_role can still bypass RLS; see ADR 010 for that boundary.

-- Keep platform admin privilege out of the business-role column.
UPDATE public.profiles SET role_status = 'general' WHERE role_status = 'admin';
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_status_check;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_status_check
  CHECK (role_status IN ('general', 'venue_pending', 'venue_approved'));

-- Profiles: admins may read only their own profile row, like any other user.
DROP POLICY IF EXISTS profiles_read_all ON public.profiles;
CREATE POLICY profiles_read_non_admin ON public.profiles
  FOR SELECT TO authenticated
  USING (COALESCE(auth.jwt() ->> 'role', '') <> 'admin');
CREATE POLICY profiles_read_self_admin ON public.profiles
  FOR SELECT TO authenticated
  USING ((select auth.uid()) = id AND (auth.jwt() ->> 'role') = 'admin');

-- Reports, issues and comments are private to the person who submitted them.
DROP POLICY IF EXISTS reports_read_owner ON public.reports;
CREATE POLICY reports_read_owner ON public.reports
  FOR SELECT TO authenticated
  USING ((select auth.uid()) = reporter_id);

DROP POLICY IF EXISTS issues_read_owner ON public.issues;
CREATE POLICY issues_read_owner ON public.issues
  FOR SELECT TO authenticated
  USING ((select auth.uid()) = reporter_id);

DROP POLICY IF EXISTS issues_update_admin ON public.issues;

DROP POLICY IF EXISTS issue_comments_read_members ON public.issue_comments;
CREATE POLICY issue_comments_read_members ON public.issue_comments
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.issues i
    WHERE i.id = issue_id AND i.reporter_id = (select auth.uid())
  ));

DROP POLICY IF EXISTS issue_comments_insert_auth ON public.issue_comments;
CREATE POLICY issue_comments_insert_reporter ON public.issue_comments
  FOR INSERT TO authenticated
  WITH CHECK (
    profile_id = (select auth.uid())
    AND EXISTS (
      SELECT 1 FROM public.issues i
      WHERE i.id = issue_id AND i.reporter_id = (select auth.uid())
    )
  );

-- Audit records are visible only to the affected user. Admin actions remain auditable
-- without exposing the audit payload to the administrator through the Data API.
DROP POLICY IF EXISTS audit_logs_admin_read ON public.audit_logs;

-- Registration answers and registration rows do not get an admin exception.
DROP POLICY IF EXISTS registrations_read_self_host_admin ON public.event_registrations;
CREATE POLICY registrations_read_self_host ON public.event_registrations
  FOR SELECT TO authenticated
  USING (
    profile_id = (select auth.uid())
    OR EXISTS (
      SELECT 1 FROM public.events e
      WHERE e.id = event_id AND e.creator_id = (select auth.uid())
    )
  );

DROP POLICY IF EXISTS reg_responses_read_self_host_admin ON public.event_registration_responses;
CREATE POLICY reg_responses_read_self_host ON public.event_registration_responses
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1
    FROM public.event_registrations er
    WHERE er.id = registration_id
      AND (
        er.profile_id = (select auth.uid())
        OR EXISTS (
          SELECT 1 FROM public.events e
          WHERE e.id = er.event_id AND e.creator_id = (select auth.uid())
        )
      )
  ));

-- Metadata-only moderation queue. It intentionally omits reporter identity and details.
CREATE OR REPLACE FUNCTION public.get_admin_report_queue()
RETURNS TABLE (
  id uuid,
  category text,
  status text,
  target_profile_id uuid,
  target_event_id uuid,
  created_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF (select auth.jwt() ->> 'role') <> 'admin' THEN
    RAISE EXCEPTION 'admin role required' USING errcode = '42501';
  END IF;

  RETURN QUERY
  SELECT r.id, r.category, r.status, r.target_profile_id, r.target_event_id, r.created_at
  FROM public.reports r
  WHERE r.status IN ('open', 'triaging')
  ORDER BY r.created_at DESC;
END;
$$;

REVOKE ALL ON FUNCTION public.get_admin_report_queue() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_admin_report_queue() TO authenticated;

-- Controlled backend write: merge moderation status without returning or selecting
-- the user's existing metadata to the admin caller.
CREATE OR REPLACE FUNCTION public.set_profile_moderation_status(target_id uuid, moderation_status text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF (select auth.jwt() ->> 'role') NOT IN ('admin', 'service_role') THEN
    RAISE EXCEPTION 'controlled backend required' USING errcode = '42501';
  END IF;

  UPDATE public.profiles
  SET metadata = jsonb_set(
    COALESCE(metadata, '{}'::jsonb),
    '{moderation_status}',
    to_jsonb(moderation_status),
    true
  )
  WHERE id = target_id;
END;
$$;

REVOKE ALL ON FUNCTION public.set_profile_moderation_status(uuid, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.set_profile_moderation_status(uuid, text) TO service_role;

-- END HISTORICAL MIGRATION: 20260810061600_admin_privacy_boundary.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260810062246_add_notification_realtime_broadcast.sql
--
-- Notify online recipients without exposing notification contents.
-- Historical notification state remains in public.notifications and is read through RLS.

CREATE SCHEMA IF NOT EXISTS private;

CREATE OR REPLACE FUNCTION private.broadcast_new_notification()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  PERFORM realtime.send(
    jsonb_build_object('notification_id', NEW.id, 'refresh', true),
    'new_notification',
    'user:' || NEW.recipient_profile_id::text,
    true
  );
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.broadcast_new_notification() FROM PUBLIC;

DROP TRIGGER IF EXISTS trg_broadcast_new_notification ON public.notifications;
CREATE TRIGGER trg_broadcast_new_notification
AFTER INSERT ON public.notifications
FOR EACH ROW
EXECUTE FUNCTION private.broadcast_new_notification();

-- Supabase enables RLS on the platform-managed realtime.messages table by
-- default. The migration role is not the owner of that table, so do not run
-- owner-only ALTER TABLE DDL here; only manage the authorization policy.

DROP POLICY IF EXISTS notifications_realtime_receive_self ON realtime.messages;
CREATE POLICY notifications_realtime_receive_self
ON realtime.messages
FOR SELECT
TO authenticated
USING (topic = 'user:' || (select auth.uid())::text);

-- END HISTORICAL MIGRATION: 20260810062246_add_notification_realtime_broadcast.sql

--
-- BEGIN HISTORICAL MIGRATION: 20260810100000_create_direct_messaging.sql
--
-- Direct messaging: one-to-one conversations for mutually accepted connections.

CREATE TABLE IF NOT EXISTS public.direct_conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  participant_one_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  participant_two_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT direct_conversations_participant_order
    CHECK (participant_one_id < participant_two_id),
  CONSTRAINT direct_conversations_unique_pair
    UNIQUE (participant_one_id, participant_two_id)
);

CREATE TABLE IF NOT EXISTS public.direct_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL REFERENCES public.direct_conversations(id) ON DELETE CASCADE,
  sender_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL CHECK (char_length(btrim(content)) BETWEEN 1 AND 4000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_direct_messages_conversation_created_at
  ON public.direct_messages (conversation_id, created_at);

CREATE INDEX IF NOT EXISTS idx_direct_conversations_participants
  ON public.direct_conversations (participant_one_id, participant_two_id);

ALTER TABLE public.direct_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.direct_messages ENABLE ROW LEVEL SECURITY;

-- The RPC sets this transaction-local marker, so direct table inserts cannot
-- create conversations while still keeping the RPC SECURITY INVOKER.
CREATE OR REPLACE FUNCTION public.create_direct_conversation(p_other_profile_id UUID)
RETURNS TABLE (id UUID)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  current_user_id UUID := auth.uid();
  first_id UUID;
  second_id UUID;
  conversation_id UUID;
BEGIN
  IF current_user_id IS NULL THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;
  IF p_other_profile_id IS NULL OR p_other_profile_id = current_user_id THEN
    RAISE EXCEPTION 'invalid conversation participant';
  END IF;

  first_id := LEAST(current_user_id, p_other_profile_id);
  second_id := GREATEST(current_user_id, p_other_profile_id);

  IF EXISTS (
    SELECT 1 FROM public.blocks
    WHERE (blocker_id = current_user_id AND blocked_id = p_other_profile_id)
       OR (blocker_id = p_other_profile_id AND blocked_id = current_user_id)
  ) THEN
    RAISE EXCEPTION 'conversation unavailable';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.connections
    WHERE requester_id = current_user_id
      AND receiver_id = p_other_profile_id
      AND status = 'accepted'
  ) OR NOT EXISTS (
    SELECT 1 FROM public.connections
    WHERE requester_id = p_other_profile_id
      AND receiver_id = current_user_id
      AND status = 'accepted'
  ) THEN
    RAISE EXCEPTION 'accepted connection required';
  END IF;

  PERFORM set_config('app.direct_conversation_rpc', 'on', true);
  INSERT INTO public.direct_conversations (participant_one_id, participant_two_id)
  VALUES (first_id, second_id)
  ON CONFLICT (participant_one_id, participant_two_id) DO NOTHING;

  SELECT c.id INTO conversation_id
  FROM public.direct_conversations AS c
  WHERE c.participant_one_id = first_id
    AND c.participant_two_id = second_id;

  RETURN QUERY SELECT conversation_id;
END;
$$;

REVOKE ALL ON FUNCTION public.create_direct_conversation(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_direct_conversation(UUID) TO authenticated;

CREATE POLICY direct_conversations_select_participant
  ON public.direct_conversations FOR SELECT TO authenticated
  USING (
    (participant_one_id = (SELECT auth.uid()) OR participant_two_id = (SELECT auth.uid()))
    AND EXISTS (
      SELECT 1 FROM public.connections c1
      WHERE c1.requester_id = participant_one_id
        AND c1.receiver_id = participant_two_id
        AND c1.status = 'accepted'
    )
    AND EXISTS (
      SELECT 1 FROM public.connections c2
      WHERE c2.requester_id = participant_two_id
        AND c2.receiver_id = participant_one_id
        AND c2.status = 'accepted'
    )
    AND NOT EXISTS (
      SELECT 1 FROM public.blocks b
      WHERE (b.blocker_id = participant_one_id AND b.blocked_id = participant_two_id)
         OR (b.blocker_id = participant_two_id AND b.blocked_id = participant_one_id)
    )
  );

CREATE POLICY direct_conversations_insert_rpc_only
  ON public.direct_conversations FOR INSERT TO authenticated
  WITH CHECK (
    current_setting('app.direct_conversation_rpc', true) = 'on'
    AND (participant_one_id = (SELECT auth.uid()) OR participant_two_id = (SELECT auth.uid()))
  );

CREATE POLICY direct_messages_select_participant
  ON public.direct_messages FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.direct_conversations c
    WHERE c.id = direct_messages.conversation_id
  ));

CREATE POLICY direct_messages_insert_participant
  ON public.direct_messages FOR INSERT TO authenticated
  WITH CHECK (
    sender_id = (SELECT auth.uid())
    AND EXISTS (
      SELECT 1 FROM public.direct_conversations c
      WHERE c.id = direct_messages.conversation_id
    )
  );

-- Realtime authorization is evaluated when the private channel is joined.
CREATE POLICY direct_messages_realtime_select
  ON realtime.messages FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.direct_conversations c
      WHERE realtime.messages.topic = 'direct-conversation:' || c.id::text
        AND (c.participant_one_id = (SELECT auth.uid()) OR c.participant_two_id = (SELECT auth.uid()))
        AND EXISTS (
          SELECT 1 FROM public.connections c1
          WHERE c1.requester_id = c.participant_one_id
            AND c1.receiver_id = c.participant_two_id
            AND c1.status = 'accepted'
        )
        AND EXISTS (
          SELECT 1 FROM public.connections c2
          WHERE c2.requester_id = c.participant_two_id
            AND c2.receiver_id = c.participant_one_id
            AND c2.status = 'accepted'
        )
        AND NOT EXISTS (
          SELECT 1 FROM public.blocks b
          WHERE (b.blocker_id = c.participant_one_id AND b.blocked_id = c.participant_two_id)
             OR (b.blocker_id = c.participant_two_id AND b.blocked_id = c.participant_one_id)
        )
    )
  );

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.direct_messages;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

-- END HISTORICAL MIGRATION: 20260810100000_create_direct_messaging.sql

